### ISSUE TITLE
Incorrect urls constructed (too many forward slashes)

### ISSUE THREAD

**Issue by yvandermeer** [yvandermeer/django-http-proxy#11]
The bug is in [views.py](https://bitbucket.org/yvandermeer/django-http-proxy/src/ddce7da742ad4c6e6552b04e4f1bcb54b50c8f71/httpproxy/views.py?at=default#cl-82):

```
request_url = u'%s/%s' % (self.base_url, url)
```

should be:

```
request_url = u'%s%s' % (self.base_url, url)
```

`normalize_request` already prefixes urls with a forward slash.

---
- Bitbucket: https://bitbucket.org/yvandermeer/django-http-proxy/issue/11
- Originally reported by: [blurback](http://bitbucket.org/blurback)
- Originally created at: 2013-05-06T22:03:40.126

**Comment by bhoomit** [comment]
When are you going to merge this thing?
